openapi: 3.0.1
info:
  title: will be replaced
  description: This information will be replaced by the SpringFox config information
  version: 0.0.1
paths:
  /statistics/consultant:
    get:
      tags:
        - statistics-controller
      summary: 'Returns statistical data for a consultant. [Authorization: consultant]'
      operationId: getConsultantStatistics
      responses:
        200:
          description: OK - successfull operation
        400:
          description: BAD REQUEST - invalid/incomplete request or body object
        403:
          description: FORBIDDEN - no/invalid CSRF token
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition
      security:
        - Bearer: [ ]
  /statistics/consultant/csv:
    get:
      tags:
        - statistics-controller
      summary: 'Returns statistical data for a consultant as csv file. [Authorization: consultant]'
      operationId: getConsultantStatisticsCsv
      responses:
        200:
          description: OK - successfull operation
        400:
          description: BAD REQUEST - invalid/incomplete request or body object
        403:
          description: FORBIDDEN - no/invalid CSRF token
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition
      security:
        - Bearer: [ ]

components:

  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
